/**
 * CadencePlan MVP — single-page app entry (Sprint 4 + Sprint 5).
 *
 * Sprint 5 additions:
 *   - ActivityService / VarianceService wired
 *   - START_ACTIVITY handler (SCHEDULED → IN_PROGRESS)
 *   - OPEN_CLOSE_DIALOG + SUBMIT_CLOSE_DIALOG + CLOSE_CLOSE_DIALOG
 *   - OPEN_SKIP_MODAL + SUBMIT_SKIP_MODAL + CLOSE_SKIP_MODAL
 *   - Fine-tune drawer + re-compose pipeline (P1-T2)
 *   - InfeasibleBanner (P2-T1)
 *   - SmartDefaults ensureUser() on boot
 *
 * This file is the ONLY place that:
 *   - calls `document.*` (via `js/ui/mount.js` helpers)
 *   - reads `window.location.hash`
 *   - attaches `hashchange` listeners
 *   - writes state-dependent UI
 *
 * Every other module is pure: takes data in, returns strings / values out.
 */

import { boot } from './boot.js';
import { LocalStorageRepository } from './persistence/LocalStorageRepository.js';
import { EventBus } from './events/EventBus.js';
import { ClockService } from './services/ClockService.js';
import { CatalogService, CATALOG_KEY } from './services/CatalogService.js';
import { ComposerService } from './services/ComposerService.js';
import { VarianceService } from './services/VarianceService.js';
import { ActivityService } from './services/ActivityService.js';
import { ReflectionService } from './services/ReflectionService.js';
import { FrictionService } from './services/FrictionService.js';
import { KaizenService } from './services/KaizenService.js';
import { OpportunityService } from './services/OpportunityService.js';
import { WeeklyComposerService } from './services/WeeklyComposerService.js';
import { ensureUser } from './services/SmartDefaults.js';
import {
  CycleProposed,
  CycleAccepted,
  CycleRejected,
  ComposerInfeasible,
  ActivityStarted,
  ActivityCompleted,
  VarianceLogged,
  ReflectionStubbed,
  ReflectionCaptured,
  FrictionSignalCaptured,
  KaizenPromoted,
  KaizenBaselineLocked,
  KaizenRemeasurementStarted,
  KaizenRemeasured,
  KaizenClosed,
  KaizenAbandoned,
  OpportunityCreated,
  OpportunityPromoted,
  OpportunityDeferred,
  OpportunityRejected,
  WeeklyCycleProposed,
  WeeklyCycleAccepted,
  KaizenStepCompleted,
  KaizenStepScheduled
} from './events/events.js';
import { BROWSER_CATALOG } from './catalog/browserSeed.js';
import { getFullCatalog } from './catalog/fullCatalog.js';
import { AppShell } from './ui/AppShell.js';
import { Today } from './ui/pages/Today.js';
import { Kaizen as KaizenPage } from './ui/pages/Kaizen.js';
import { Portfolio } from './ui/pages/Portfolio.js';
import { Catalog as CatalogPage } from './ui/pages/Catalog.js';
import { Week as WeekPage } from './ui/pages/Week.js';
import { PlaceholderPage } from './ui/pages/PlaceholderPage.js';
import { parseArtifactFields } from './ui/components/OutputArtifactDialog.js';
import { ReflectionSheet } from './ui/components/ReflectionSheet.js';
import {
  BaselineDialog,
  extractBaselineFields
} from './ui/components/BaselineDialog.js';
import {
  RemeasurementDialog,
  extractRemeasurementFields
} from './ui/components/RemeasurementDialog.js';
import { KaizenCloseDialog } from './ui/components/KaizenCloseDialog.js';
import {
  mountHtml,
  attachRootClickListener
} from './ui/mount.js';
import {
  createRouteListener,
  parseHash,
  buildHash
} from './ui/router.js';

/**
 * Default user — single-user MVP. A future sprint replaces this with a
 * real Settings-driven User row.
 */
export const DEFAULT_USER = Object.freeze({
  id: 'user_phil_mvp',
  name: 'Phil',
  email: 'phil@mediafier.ai',
  role: ['PRACTITIONER'],
  dailyCapacityMinutes: 480,
  workDays: [1, 2, 3, 4, 5],
  sprintAnchorDate: '2026-04-20',
  timezone: 'America/Los_Angeles',
  deepSlicePreference: '2x2h',
  createdAt: '2026-04-01T00:00:00Z'
});

const APP_ROOT_ID = 'app-root';

/**
 * Build the app services. Exported for tests and for the browser
 * bootstrapper. Side effects: reads/writes localStorage (via the repo),
 * seeds the catalog if empty.
 *
 * @param {{storage?: object, clock?: ClockService}} [deps]
 * @returns {object}
 */
export function buildServices(deps = {}) {
  const repo = new LocalStorageRepository({
    storage: deps.storage ?? globalThis.localStorage
  });
  const bus = new EventBus();
  const clock = deps.clock ?? new ClockService();

  boot(repo, { now: () => clock.nowDate() });

  const catalogService = new CatalogService({ repo });
  // Seed only if empty — idempotent across reloads.
  const existing = repo.read(CATALOG_KEY);
  if (!existing || Object.keys(existing).length === 0) {
    // Browser path uses the 9-entry browserSeed until fullCatalog.json is
    // present (generated by exportFullCatalog). Tests use the full
    // pipeline via their own CatalogService.seed() calls.
    catalogService.seed(BROWSER_CATALOG.map((c) => ({ ...c })));
  }

  const composerService = new ComposerService({
    repo,
    bus,
    clock,
    catalogService
  });
  const varianceService = new VarianceService({ repo, bus, clock });
  const activityService = new ActivityService({
    repo,
    bus,
    clock,
    varianceService,
    catalogService,
    composerService
  });

  // Sprint 6 — reflection loop + kaizen services.
  const frictionService = new FrictionService({ repo, bus, clock });
  const reflectionService = new ReflectionService({ repo, bus, clock });
  reflectionService.setFrictionService(frictionService);
  const kaizenService = new KaizenService({ repo, bus, clock });
  kaizenService.setFrictionService(frictionService);
  // Sprint 10b Pass B — step methods need the catalog.
  kaizenService.setCatalogService({
    list: () => catalogService.list(DEFAULT_USER.id)
  });

  // Sprint 7 — Opportunity intake service.
  const opportunityService = new OpportunityService({
    repo,
    bus,
    clock,
    kaizenService
  });

  // Sprint 9 — Weekly composer service.
  const weeklyComposerService = new WeeklyComposerService({
    repo,
    bus,
    clock,
    composerService,
    catalogService,
    kaizenService,
    activityService
  });

  // Ensure a User row exists with smart defaults (Sprint 5 P0-T2).
  ensureUser({
    repo,
    clock,
    userId: DEFAULT_USER.id,
    name: DEFAULT_USER.name,
    email: DEFAULT_USER.email
  });

  return {
    repo,
    bus,
    clock,
    catalogService,
    composerService,
    varianceService,
    activityService,
    reflectionService,
    frictionService,
    kaizenService,
    opportunityService,
    weeklyComposerService
  };
}

/**
 * Build a composer input from the default user. Accepts optional
 * overrides for the fine-tune drawer: `capacityMinutesOverride` and
 * `externalMinutesToday` land on composerInputsSnapshot.
 *
 * @param {ClockService} clock
 * @param {{capacityMinutesOverride?: number, externalMinutesToday?: number, activeKaizenId?: string|null}} [overrides]
 * @returns {object}
 */
export function buildComposerInput(clock, overrides = {}) {
  const date = clock.nowDate().toISOString().slice(0, 10);
  const effectiveCapacity =
    typeof overrides.capacityMinutesOverride === 'number'
      ? overrides.capacityMinutesOverride
      : DEFAULT_USER.dailyCapacityMinutes;
  const effectiveExternal =
    typeof overrides.externalMinutesToday === 'number'
      ? overrides.externalMinutesToday
      : 0;

  const input = {
    cycleType: 'DAILY',
    userId: DEFAULT_USER.id,
    date,
    role: [...DEFAULT_USER.role],
    dailyCapacityMinutes: effectiveCapacity,
    externalMinutesToday: effectiveExternal,
    // Sprint 5: expose the override for downstream Composition snapshot.
    capacityMinutesOverride:
      typeof overrides.capacityMinutesOverride === 'number'
        ? overrides.capacityMinutesOverride
        : null,
    sprintPhase: 'EXECUTION',
    sprintAnchorDate: DEFAULT_USER.sprintAnchorDate,
    user: {
      deepSlicePreference: DEFAULT_USER.deepSlicePreference,
      sprintAnchorDate: DEFAULT_USER.sprintAnchorDate
    },
    activeKaizen:
      overrides.activeKaizenId === null
        ? null
        : {
            id: overrides.activeKaizenId ?? 'k_cadenceplan_mvp',
            title: 'Ship CadencePlan MVP',
            state: 'ACTIVE',
            projectType: 'DMAIC',
            nextStepActivityNumber: 34
          },
    varianceQueue: [],
    priorCompositions: [],
    signals: {
      inboxOverThreshold: false,
      documentAwaitingReview: [],
      innovationStageReady: []
    },
    pdcaExperiment: null
  };
  return input;
}

/**
 * App state — the single render-fed object. `renderApp()` reads from
 * this (plus the repo) to produce HTML; handlers mutate it and call
 * renderApp() again.
 */
function createState() {
  return {
    route: 'today',
    params: {},
    composerLoading: false,
    infeasibleExplain: null,
    lastError: null,
    // Sprint 5: Fine-tune drawer state.
    fineTune: {
      open: false,
      capacityMinutes: DEFAULT_USER.dailyCapacityMinutes,
      externalMinutesToday: 0,
      activeKaizenId: 'k_cadenceplan_mvp',
      availableKaizens: [],
      // Pre-fine-tune snapshot for Cancel to restore.
      _snapshotBeforeChange: null
    },
    // Sprint 5: open dialog state (CLOSE artifact modal OR SKIP reason modal).
    openDialog: null,
    // Sprint 6: reflection sheet (opens on ActivityCompleted).
    reflectionSheet: null,
    // Sprint 6: weekly reflection wizard state.
    wizard: null,
    // Sprint 7 P0-T5 / T6: Portfolio state.
    portfolio: {
      intakeForm: null,           // when truthy, OpportunityIntakeForm is shown
      expandedOpportunityId: null, // P1-T1 inline expand
      oppFilter: 'all',
      oppSort: 'newest'
    },
    // Sprint 7 P0-T7: Catalog page view toggle (list / bucket).
    catalogView: 'list',
    // Sprint 8: Kaizen HARD RULE close loop dialogs.
    baselineDialog: null,          // { kaizenId, fields..., errorName?, errorMessage? }
    remeasurementDialog: null,     // { kaizenId, currentValue, evidenceSchema, evidenceValue, errorName? }
    closeKaizenDialog: null,       // { kaizenId, lessonsLearned, errorName? }
    kaizenAbandonForm: null,       // { kaizenId } — when truthy, inline abandon form open
    // Sprint 10b Pass B — Portfolio expand/collapse for projects.
    expandedKaizenId: null
  };
}

/**
 * LocalStorage key for persisted Portfolio filter/sort preferences (P1-T3).
 */
export const PORTFOLIO_PREFS_KEY = 'bamx:v1:portfolioPrefs';

/**
 * Load persisted Portfolio filter/sort prefs (best-effort).
 *
 * @param {object} repo
 * @returns {{oppFilter?: string, oppSort?: string}|null}
 */
function loadPortfolioPrefs(repo) {
  try {
    return repo.read(PORTFOLIO_PREFS_KEY) ?? null;
  } catch {
    return null;
  }
}

/**
 * Persist Portfolio filter/sort prefs (best-effort; never throws).
 *
 * @param {object} repo
 * @param {{oppFilter: string, oppSort: string}} prefs
 */
function savePortfolioPrefs(repo, prefs) {
  try {
    repo.write(PORTFOLIO_PREFS_KEY, prefs);
  } catch {
    /* swallow */
  }
}

/**
 * Sprint 10c: list "orphan" ScheduledActivity rows for a given date.
 *
 * KaizenService.scheduleStep creates rows with `compositionId: null` so
 * the user can schedule a standard-work step directly from Portfolio
 * without an active Composition. ComposerService.getActiveComposition
 * filters those rows out (it only returns children of the latest
 * PROPOSED/ACCEPTED composition), so without this helper those rows
 * persist in storage but never render anywhere.
 *
 * @param {{read: (key: string) => any}} repo
 * @param {string} dateIso   YYYY-MM-DD
 * @returns {object[]}
 */
export function listOrphanActivitiesForDate(repo, dateIso) {
  if (!repo || typeof dateIso !== 'string' || dateIso.length < 10) return [];
  const acts = repo.read('bamx:v1:activities') ?? {};
  return Object.values(acts).filter(
    (a) =>
      a &&
      (a.compositionId == null) &&
      typeof a.plannedStartAt === 'string' &&
      a.plannedStartAt.slice(0, 10) === dateIso
  );
}

/**
 * Sprint 10c: merge orphan activities (from scheduleStep) into the
 * active state returned by `ComposerService.getActiveComposition`. If no
 * composition exists yet but orphans are present, synthesize a minimal
 * ACCEPTED composition so Today can render them — the composition id is
 * a stable sentinel ('synth_orphan_day') and callers can detect the
 * synthesized state via `composition.synthesizedForOrphans === true`.
 *
 * @param {null | {composition: object, activities: object[]}} activeState
 * @param {object[]} orphans
 * @returns {null | {composition: object, activities: object[]}}
 */
export function mergeOrphanActivities(activeState, orphans) {
  if (!Array.isArray(orphans) || orphans.length === 0) return activeState;
  if (activeState) {
    return {
      composition: activeState.composition,
      activities: [...activeState.activities, ...orphans]
    };
  }
  const plannedByBucket = { PROJECT: 0, COMMUNICATION: 0, CI: 0 };
  for (const a of orphans) {
    if (plannedByBucket[a.bucket] !== undefined) {
      plannedByBucket[a.bucket] += Number(a.plannedDurationMinutes ?? 0);
    }
  }
  const anchor = orphans[0];
  const dateIso = typeof anchor.plannedStartAt === 'string'
    ? anchor.plannedStartAt.slice(0, 10)
    : '';
  return {
    composition: {
      id: 'synth_orphan_day',
      userId: anchor.userId ?? '',
      date: dateIso,
      state: 'ACCEPTED',
      proposedAt: anchor.createdAt ?? '',
      acceptedAt: anchor.createdAt ?? '',
      capacityMinutes: 480,
      bucketTargets: { PROJECT: 240, COMMUNICATION: 120, CI: 120 },
      bucketFloors: { PROJECT: 120, COMMUNICATION: 60, CI: 60 },
      bucketCeilings: { PROJECT: 264, COMMUNICATION: 150, CI: 150 },
      plannedByBucket,
      synthesizedForOrphans: true
    },
    activities: [...orphans]
  };
}

/**
 * Render the entire app into the DOM. Pure shell around the pure page
 * components; real DOM only via `mountHtml`.
 *
 * @param {object} services
 * @param {object} state
 */
export function renderApp(services, state) {
  const {
    composerService,
    kaizenService,
    frictionService,
    opportunityService,
    catalogService,
    weeklyComposerService
  } = services;
  let pageHtml;

  if (state.route === 'today') {
    const activeState = composerService.getActiveComposition(DEFAULT_USER.id);
    // Sprint 10c fix: scheduleStep creates ScheduledActivity rows with
    // compositionId:null; getActiveComposition filters them out. Merge
    // today's orphan activities back into the active state so they show
    // up on the Today page.
    const todayDate = services.clock.now().slice(0, 10);
    const orphans = listOrphanActivitiesForDate(services.repo, todayDate);
    const mergedActiveState = mergeOrphanActivities(activeState, orphans);
    const daysSinceSignup = computeDaysSinceSignup(
      DEFAULT_USER.createdAt,
      services.clock.now()
    );
    // Build the kaizenId → title lookup so activity blocks can render a
    // "part of: [title]" chip across all states (Sprint 10 backlog item #2).
    const kaizenTitleById = {};
    if (kaizenService && typeof kaizenService.list === 'function') {
      for (const k of kaizenService.list({ userId: DEFAULT_USER.id }) ?? []) {
        if (k && typeof k.id === 'string') {
          kaizenTitleById[k.id] = k.title ?? k.name ?? k.id;
        }
      }
    }
    const todayHtml = Today({
      activeState: mergedActiveState,
      loading: state.composerLoading,
      isFirstRun: activeState === null && daysSinceSignup <= 1,
      infeasibleExplain: state.infeasibleExplain,
      adherence: {
        adherencePct: null,
        acceptancePct: null,
        kaizenDeltaPct: null,
        daysSinceSignup
      },
      nowIso: services.clock.now(),
      fineTune: state.fineTune,
      openDialog: state.openDialog,
      kaizenTitleById
    });
    const reflectionSheetHtml = state.reflectionSheet
      ? ReflectionSheet(state.reflectionSheet)
      : '';
    pageHtml = `${todayHtml}${reflectionSheetHtml}`;
  } else if (state.route === 'portfolio' && opportunityService && kaizenService) {
    const userId = DEFAULT_USER.id;
    const activeKaizens = [
      ...kaizenService.listByState(userId, 'ACTIVE'),
      ...kaizenService.listByState(userId, 'IN_REMEASUREMENT')
    ];
    const closedKaizens = kaizenService.listByState(userId, 'CLOSED');
    const remeasurementsByKaizenId = {};
    for (const k of closedKaizens) {
      const rm = kaizenService.getRemeasurementForKaizen(k.id);
      if (rm) remeasurementsByKaizenId[k.id] = rm;
    }
    const opportunities = opportunityService.list({
      userId,
      includeTerminal: true
    });
    const catalogEntries = catalogService ? catalogService.list(userId) : [];
    const completedStepsByKaizenId =
      typeof kaizenService.getCompletedStepsByKaizenId === 'function'
        ? kaizenService.getCompletedStepsByKaizenId()
        : {};
    pageHtml = Portfolio({
      activeKaizens,
      closedKaizens,
      remeasurementsByKaizenId,
      opportunities,
      catalogEntries,
      completedStepsByKaizenId,
      expandedKaizenId: state.expandedKaizenId ?? null,
      nowIso: services.clock.now(),
      intakeForm: state.portfolio?.intakeForm ?? null,
      expandedOpportunityId: state.portfolio?.expandedOpportunityId ?? null,
      oppFilter: state.portfolio?.oppFilter ?? 'all',
      oppSort: state.portfolio?.oppSort ?? 'newest'
    });
  } else if (state.route === 'catalog' && catalogService) {
    const userId = DEFAULT_USER.id;
    const entries = catalogService.list(userId);
    pageHtml = CatalogPage({
      entries,
      view: state.catalogView ?? 'list'
    });
  } else if (state.route === 'week' && weeklyComposerService) {
    const userId = DEFAULT_USER.id;
    const weekStart =
      state.weekStartOverride ?? computeMondayIso(services.clock.now());
    const weeklyComposition =
      weeklyComposerService.getLatestProposed(userId);
    pageHtml = WeekPage({
      weeklyComposition,
      weekStart
    });
  } else if (state.route === 'kaizen' && kaizenService && frictionService) {
    const userId = DEFAULT_USER.id;
    const active =
      kaizenService.listByState(userId, 'ACTIVE')[0] ??
      kaizenService.listByState(userId, 'IN_REMEASUREMENT')[0] ??
      null;
    const drafts = kaizenService.listByState(userId, 'DRAFT');
    const baseline = active
      ? kaizenService.getBaselineForKaizen(active.id)
      : null;
    const remeasurement = active
      ? kaizenService.getRemeasurementForKaizen(active.id)
      : null;
    const openFrictionSignals = frictionService.list({
      userId,
      status: 'OPEN'
    });
    const kaizenHtml = KaizenPage({
      activeKaizen: active,
      draftKaizens: drafts,
      baseline,
      remeasurement,
      openFrictionSignals,
      wizardState: state.wizard,
      abandonForm: state.kaizenAbandonForm
    });
    const dialogHtml = renderKaizenDialogs(services, state);
    pageHtml = `${kaizenHtml}${dialogHtml}`;
  } else {
    pageHtml = PlaceholderPage({ route: state.route });
  }

  const shellHtml = AppShell({ route: state.route, pageHtml });
  mountHtml(APP_ROOT_ID, shellHtml);
}

/**
 * Render any open Sprint 8 Kaizen dialogs into a string (baseline /
 * remeasurement / close). Empty string when none are open.
 *
 * @param {object} services
 * @param {object} state
 * @returns {string}
 */
function renderKaizenDialogs(services, state) {
  let html = '';
  if (state.baselineDialog) {
    html += BaselineDialog(state.baselineDialog);
  }
  if (state.remeasurementDialog) {
    const bd = services.kaizenService.getBaselineForKaizen(
      state.remeasurementDialog.kaizenId
    );
    const k = services.kaizenService.get(state.remeasurementDialog.kaizenId);
    html += RemeasurementDialog({
      ...state.remeasurementDialog,
      baseline: bd,
      metricDirection: k?.metricDirection ?? 'higher_is_better'
    });
  }
  if (state.closeKaizenDialog) {
    const k = services.kaizenService.get(state.closeKaizenDialog.kaizenId);
    const bd = services.kaizenService.getBaselineForKaizen(
      state.closeKaizenDialog.kaizenId
    );
    const rm = services.kaizenService.getRemeasurementForKaizen(
      state.closeKaizenDialog.kaizenId
    );
    html += KaizenCloseDialog({
      ...state.closeKaizenDialog,
      kaizen: k,
      baseline: bd,
      remeasurement: rm
    });
  }
  return html;
}

/**
 * Compute the ISO date (YYYY-MM-DD) of the Monday of the week containing
 * `nowIso`. Always returns a Monday. Used by the Week page to default the
 * "Plan this week" payload.
 *
 * @param {string} nowIso
 * @returns {string}
 */
export function computeMondayIso(nowIso) {
  const d = new Date(nowIso);
  if (Number.isNaN(d.getTime())) {
    return new Date().toISOString().slice(0, 10);
  }
  // getUTCDay: 0 = Sun, 1 = Mon, ... 6 = Sat. Roll back to Monday.
  const wd = d.getUTCDay();
  const offset = wd === 0 ? 6 : wd - 1; // Sun → 6 days back, Mon → 0, Tue → 1, ...
  const mon = new Date(d.getTime());
  mon.setUTCDate(mon.getUTCDate() - offset);
  const y = mon.getUTCFullYear();
  const m = String(mon.getUTCMonth() + 1).padStart(2, '0');
  const day = String(mon.getUTCDate()).padStart(2, '0');
  return `${y}-${m}-${day}`;
}

/**
 * Compute days since signup, rounded down.
 *
 * @param {string} createdAtIso
 * @param {string} nowIso
 * @returns {number}
 */
export function computeDaysSinceSignup(createdAtIso, nowIso) {
  const a = new Date(createdAtIso);
  const b = new Date(nowIso);
  if (Number.isNaN(a.getTime()) || Number.isNaN(b.getTime())) return 0;
  const ms = b.getTime() - a.getTime();
  if (ms < 0) return 0;
  return Math.floor(ms / (24 * 60 * 60 * 1000));
}

/**
 * Look up an activity + its catalog entry. Returns {activity, entry} or
 * null if either is missing.
 *
 * @param {object} services
 * @param {string} activityId
 * @returns {{activity: object, entry: object|null} | null}
 */
function lookupActivity(services, activityId) {
  const acts = services.repo.read('bamx:v1:activities') ?? {};
  const activity = acts[activityId];
  if (!activity) return null;
  const list = services.catalogService.list(DEFAULT_USER.id);
  const entry = list.find((c) => c && c.id === activity.catalogEntryId) ?? null;
  return { activity, entry };
}

/**
 * Build the click handler registry.
 *
 * @param {{services: object, state: object, rerender: () => void}} scope
 */
export function buildHandlers(scope) {
  const { services, state, rerender } = scope;

  function runCompose(overrides) {
    state.composerLoading = true;
    state.lastError = null;
    state.infeasibleExplain = null;
    rerender();
    try {
      const input = buildComposerInput(services.clock, overrides);
      const result = services.composerService.composeDaily(input);
      if (result.state === 'INFEASIBLE') {
        state.infeasibleExplain = result.infeasible?.explain ?? [];
      }
    } catch (err) {
      state.lastError = err;
    } finally {
      state.composerLoading = false;
      rerender();
    }
  }

  return {
    AUTO_PLAN(_payload) {
      const ft = state.fineTune ?? null;
      const override =
        ft && typeof ft.capacityMinutes === 'number' &&
        ft.capacityMinutes !== DEFAULT_USER.dailyCapacityMinutes
          ? ft.capacityMinutes
          : undefined;
      runCompose({
        capacityMinutesOverride: override,
        externalMinutesToday: ft?.externalMinutesToday ?? 0,
        activeKaizenId: ft?.activeKaizenId ?? undefined
      });
    },

    ACCEPT(payload) {
      if (!payload || !payload.compositionId) return;
      try {
        services.composerService.accept(payload.compositionId);
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    EDIT(_payload) {
      // Edit (drag/drop composer) ships in Sprint 6.
      if (typeof globalThis.alert === 'function') {
        globalThis.alert('Edit composer ships in Sprint 6.');
      }
    },

    REJECT(payload) {
      if (!payload || !payload.compositionId) return;
      const confirmFn = globalThis.confirm ?? (() => true);
      const ok = confirmFn(
        "Reject today's plan? You'll need to build manually or wait for tomorrow."
      );
      if (!ok) return;
      try {
        services.composerService.reject(payload.compositionId);
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    // ---- Sprint 5: ScheduledActivity runtime -------------------------------

    START_ACTIVITY(payload) {
      if (!payload || !payload.activityId) return;
      try {
        services.activityService.start(payload.activityId);
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    OPEN_CLOSE_DIALOG(payload) {
      if (!payload || !payload.activityId) return;
      const looked = lookupActivity(services, payload.activityId);
      if (!looked) return;
      const schema = looked.entry?.outputArtifact?.schema ?? 'TEXT';
      state.openDialog = {
        kind: 'CLOSE',
        activityId: payload.activityId,
        schema,
        artifactDef: looked.entry?.outputArtifact ?? { schema, name: 'Output' }
      };
      rerender();
    },

    CLOSE_CLOSE_DIALOG(_payload) {
      state.openDialog = null;
      rerender();
    },

    SUBMIT_CLOSE_DIALOG(payload, ctx) {
      // Payload from form submit is the {activityId, schema} we stamped
      // on data-payload. The actual form field values are pulled off the
      // form element (if provided) via ctx.element.
      if (!payload || !payload.activityId) return;
      const schema = payload.schema ?? state.openDialog?.schema ?? 'TEXT';
      const fields = extractFormFields(ctx?.element);
      const ref = parseArtifactFields(schema, fields);
      try {
        services.activityService.close(payload.activityId, { outputArtifactRef: ref });
        state.openDialog = null;
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    OPEN_SKIP_MODAL(payload) {
      if (!payload || !payload.activityId) return;
      const looked = lookupActivity(services, payload.activityId);
      state.openDialog = {
        kind: 'SKIP',
        activityId: payload.activityId,
        activityName: looked?.entry?.name ?? looked?.activity?.name ?? payload.activityId
      };
      rerender();
    },

    CLOSE_SKIP_MODAL(_payload) {
      state.openDialog = null;
      rerender();
    },

    SUBMIT_SKIP_MODAL(payload, ctx) {
      if (!payload || !payload.activityId) return;
      const fields = extractFormFields(ctx?.element);
      const reasonCode = fields.reasonCode ?? null;
      const note = fields.note ?? null;
      try {
        services.activityService.skip(payload.activityId, { reasonCode, note });
        state.openDialog = null;
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    // ---- Sprint 5: Fine-tune drawer ----------------------------------------

    FINE_TUNE_TOGGLE(_payload) {
      if (!state.fineTune) return;
      if (!state.fineTune.open) {
        // Snapshot current settings before open, so Cancel can restore.
        state.fineTune._snapshotBeforeChange = {
          capacityMinutes: state.fineTune.capacityMinutes,
          externalMinutesToday: state.fineTune.externalMinutesToday,
          activeKaizenId: state.fineTune.activeKaizenId
        };
      }
      state.fineTune.open = !state.fineTune.open;
      rerender();
    },

    CAPACITY_CHANGE(payload) {
      if (!state.fineTune) return;
      if (!payload || typeof payload.minutes !== 'number') return;
      state.fineTune.capacityMinutes = payload.minutes;
      rerender();
    },

    EXTERNAL_MEETINGS_CHANGE(payload) {
      if (!state.fineTune) return;
      if (!payload || typeof payload.minutes !== 'number') return;
      state.fineTune.externalMinutesToday = payload.minutes;
      rerender();
    },

    PROJECT_FOCUS_CHANGE(payload, ctx) {
      if (!state.fineTune) return;
      let kaizenId = payload?.kaizenId ?? null;
      if (!kaizenId && ctx?.element && typeof ctx.element.value === 'string') {
        kaizenId = ctx.element.value || null;
      }
      state.fineTune.activeKaizenId = kaizenId;
      rerender();
    },

    FINE_TUNE_CANCEL(_payload) {
      if (!state.fineTune) return;
      const snap = state.fineTune._snapshotBeforeChange;
      if (snap) {
        state.fineTune.capacityMinutes = snap.capacityMinutes;
        state.fineTune.externalMinutesToday = snap.externalMinutesToday;
        state.fineTune.activeKaizenId = snap.activeKaizenId;
      }
      state.fineTune.open = false;
      state.fineTune._snapshotBeforeChange = null;
      rerender();
    },

    FINE_TUNE_APPLY(_payload) {
      // Discard the snapshot — the new values win.
      if (state.fineTune) {
        state.fineTune._snapshotBeforeChange = null;
        state.fineTune.open = false;
      }
      const ft = state.fineTune ?? {};
      const override =
        typeof ft.capacityMinutes === 'number' &&
        ft.capacityMinutes !== DEFAULT_USER.dailyCapacityMinutes
          ? ft.capacityMinutes
          : undefined;
      runCompose({
        capacityMinutesOverride: override,
        externalMinutesToday: ft.externalMinutesToday ?? 0,
        activeKaizenId: ft.activeKaizenId ?? undefined
      });
    },

    // ---- Sprint 6: Reflection loop ------------------------------------------

    SUBMIT_REFLECTION(payload, ctx) {
      if (!payload || !payload.reflectionId) return;
      const fields = extractFormFields(ctx?.element);
      try {
        services.reflectionService.capture(payload.reflectionId, {
          whatWentWell: fields.whatWentWell ?? null,
          whatToImprove: fields.whatToImprove ?? null,
          frictionFlag: Boolean(fields.frictionFlag),
          frictionTag: fields.frictionTag ?? null,
          frictionSummary: fields.frictionSummary ?? null,
          userId: DEFAULT_USER.id
        });
        state.reflectionSheet = null;
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    SKIP_REFLECTION(_payload) {
      state.reflectionSheet = null;
      rerender();
    },

    CLOSE_REFLECTION(_payload) {
      state.reflectionSheet = null;
      rerender();
    },

    TOGGLE_FRICTION(_payload, ctx) {
      if (!state.reflectionSheet) return;
      const el = ctx?.element;
      // If the change originated from a checkbox, use its checked state;
      // otherwise toggle.
      if (el && typeof el.checked === 'boolean') {
        state.reflectionSheet.frictionChecked = el.checked;
      } else {
        state.reflectionSheet.frictionChecked = !state.reflectionSheet.frictionChecked;
      }
      rerender();
    },

    // ---- Sprint 6: Kaizen + Weekly Reflection wizard -----------------------

    WRW_OPEN(_payload) {
      const clusters = services.frictionService.clusterByTag(DEFAULT_USER.id, 7);
      state.wizard = {
        step: 1,
        clusters,
        selectedTag: clusters[0]?.tag ?? null,
        title: '',
        problemStatement: '',
        goalStatement: '',
        errorName: null
      };
      rerender();
    },

    WRW_CLOSE(_payload) {
      state.wizard = null;
      rerender();
    },

    WRW_BACK(_payload) {
      if (!state.wizard) return;
      state.wizard.step = Math.max(1, state.wizard.step - 1);
      rerender();
    },

    WRW_NEXT(payload, ctx) {
      if (!state.wizard) return;
      // If the next action comes from the step-3 form, grab field values.
      const fields = ctx?.element ? extractFormFields(ctx.element) : {};
      if (state.wizard.step === 3) {
        if (typeof fields.title === 'string') state.wizard.title = fields.title;
        if (typeof fields.problemStatement === 'string')
          state.wizard.problemStatement = fields.problemStatement;
        if (typeof fields.goalStatement === 'string')
          state.wizard.goalStatement = fields.goalStatement;
      }
      state.wizard.step = Math.min(4, state.wizard.step + 1);
      rerender();
    },

    WRW_PICK_CLUSTER(payload) {
      if (!state.wizard) return;
      if (typeof payload?.tag === 'string') {
        state.wizard.selectedTag = payload.tag;
      }
      rerender();
    },

    WRW_SUBMIT(_payload) {
      if (!state.wizard) return;
      const cluster = (state.wizard.clusters ?? []).find(
        (c) => c.tag === state.wizard.selectedTag
      ) ?? state.wizard.clusters?.[0];
      if (!cluster) {
        state.wizard.errorName = 'NO_CLUSTER_SELECTED';
        rerender();
        return;
      }
      try {
        services.kaizenService.promote({
          userId: DEFAULT_USER.id,
          fromFrictionClusterSignalIds: cluster.signalIds,
          problemStatement: state.wizard.problemStatement,
          title: state.wizard.title,
          goalStatement: state.wizard.goalStatement ?? ''
        });
        state.wizard = null;
        // Navigate to #kaizen to see the new DRAFT.
        if (typeof globalThis.location !== 'undefined') {
          globalThis.location.hash = '#kaizen';
        }
      } catch (err) {
        state.wizard.errorName = err.name ?? 'PROMOTE_FAILED';
        state.lastError = err;
      }
      rerender();
    },

    KAIZEN_SET_GOAL(payload, ctx) {
      if (!payload || !payload.kaizenId) return;
      const fields = extractFormFields(ctx?.element);
      try {
        services.kaizenService.setGoalStatement(
          payload.kaizenId,
          fields.goalStatement ?? ''
        );
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    KAIZEN_ADD_ACTION(payload, ctx) {
      if (!payload || !payload.kaizenId) return;
      const fields = extractFormFields(ctx?.element);
      try {
        services.kaizenService.addAction(payload.kaizenId, {
          name: fields.name ?? '',
          ownerRef: fields.ownerRef ?? '',
          dueDate: fields.dueDate ?? ''
        });
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    KAIZEN_REMOVE_ACTION(payload) {
      if (!payload || !payload.kaizenId || typeof payload.index !== 'number') return;
      try {
        services.kaizenService.removeAction(payload.kaizenId, payload.index);
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    KAIZEN_MARK_ACTION_DONE(payload) {
      if (!payload || !payload.kaizenId || typeof payload.index !== 'number') return;
      try {
        services.kaizenService.markActionDone(payload.kaizenId, payload.index);
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    KAIZEN_LOCK_BASELINE(payload) {
      if (!payload || !payload.kaizenId) return;
      // Sprint 8 P0-T7: open the BaselineDialog.
      state.baselineDialog = {
        kaizenId: payload.kaizenId,
        metricName: '',
        unit: '',
        operationalDefinition: '',
        sampleSize: '',
        method: '',
        value: '',
        metricDirection: 'higher_is_better',
        targetImprovement: '',
        errorName: null,
        errorMessage: null
      };
      rerender();
    },

    CLOSE_BASELINE_DIALOG(_payload) {
      state.baselineDialog = null;
      rerender();
    },

    SUBMIT_BASELINE_DIALOG(payload, ctx) {
      if (!payload || !payload.kaizenId) return;
      const fields = extractFormFields(ctx?.element);
      const normalized = extractBaselineFields(fields);
      try {
        services.kaizenService.lockBaseline(payload.kaizenId, normalized);
        state.baselineDialog = null;
      } catch (err) {
        state.baselineDialog = {
          ...(state.baselineDialog ?? {}),
          ...normalized,
          kaizenId: payload.kaizenId,
          errorName: err.name ?? 'LOCK_FAILED',
          errorMessage: err.message ?? ''
        };
        state.lastError = err;
      }
      rerender();
    },

    KAIZEN_START_REMEASUREMENT(payload) {
      if (!payload || !payload.kaizenId) return;
      try {
        services.kaizenService.startRemeasurement(payload.kaizenId, DEFAULT_USER.id);
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    KAIZEN_OPEN_REMEASUREMENT_DIALOG(payload) {
      if (!payload || !payload.kaizenId) return;
      state.remeasurementDialog = {
        kaizenId: payload.kaizenId,
        currentValue: '',
        evidenceSchema: '',
        evidenceValue: '',
        errorName: null,
        errorMessage: null
      };
      rerender();
    },

    CLOSE_REMEASUREMENT_DIALOG(_payload) {
      state.remeasurementDialog = null;
      rerender();
    },

    REMEASUREMENT_PREVIEW_CHANGE(_payload, ctx) {
      if (!state.remeasurementDialog) return;
      const el = ctx?.element;
      if (el && typeof el.value === 'string') {
        state.remeasurementDialog.currentValue = el.value;
      }
      rerender();
    },

    SUBMIT_REMEASUREMENT_DIALOG(payload, ctx) {
      if (!payload || !payload.kaizenId) return;
      const fields = extractFormFields(ctx?.element);
      const normalized = extractRemeasurementFields(fields);
      try {
        services.kaizenService.captureRemeasurement(
          payload.kaizenId,
          DEFAULT_USER.id,
          normalized
        );
        state.remeasurementDialog = null;
      } catch (err) {
        state.remeasurementDialog = {
          ...(state.remeasurementDialog ?? {}),
          currentValue: fields.currentValue ?? '',
          evidenceSchema: fields.evidenceSchema ?? '',
          evidenceValue: fields.evidenceValue ?? '',
          errorName: err.name ?? 'CAPTURE_FAILED',
          errorMessage: err.message ?? ''
        };
        state.lastError = err;
      }
      rerender();
    },

    KAIZEN_OPEN_CLOSE_DIALOG(payload) {
      if (!payload || !payload.kaizenId) return;
      state.closeKaizenDialog = {
        kaizenId: payload.kaizenId,
        lessonsLearned: '',
        errorName: null,
        errorMessage: null
      };
      rerender();
    },

    CLOSE_CLOSE_KAIZEN_DIALOG(_payload) {
      state.closeKaizenDialog = null;
      rerender();
    },

    SUBMIT_CLOSE_KAIZEN_DIALOG(payload, ctx) {
      if (!payload || !payload.kaizenId) return;
      const fields = extractFormFields(ctx?.element);
      try {
        services.kaizenService.close(payload.kaizenId, DEFAULT_USER.id, {
          lessonsLearned: fields.lessonsLearned ?? ''
        });
        state.closeKaizenDialog = null;
      } catch (err) {
        state.closeKaizenDialog = {
          ...(state.closeKaizenDialog ?? {}),
          lessonsLearned: fields.lessonsLearned ?? '',
          errorName: err.name ?? 'CLOSE_FAILED',
          errorMessage: err.message ?? ''
        };
        state.lastError = err;
      }
      rerender();
    },

    KAIZEN_ABANDON(payload) {
      if (!payload || !payload.kaizenId) return;
      state.kaizenAbandonForm = { kaizenId: payload.kaizenId };
      rerender();
    },

    KAIZEN_CANCEL_ABANDON(_payload) {
      state.kaizenAbandonForm = null;
      rerender();
    },

    KAIZEN_CONFIRM_ABANDON(payload, ctx) {
      if (!payload || !payload.kaizenId) return;
      const fields = extractFormFields(ctx?.element);
      try {
        services.kaizenService.abandon(payload.kaizenId, DEFAULT_USER.id, {
          reason: fields.reason ?? ''
        });
        state.kaizenAbandonForm = null;
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    // ---- Sprint 7: Portfolio / Opportunity intake ---------------------------

    OPP_OPEN_INTAKE(_payload) {
      if (!state.portfolio) {
        state.portfolio = { intakeForm: null, expandedOpportunityId: null };
      }
      state.portfolio.intakeForm = {
        title: '',
        problemStatement: '',
        scope: '',
        proposedProjectType: 'AD_HOC',
        errorName: null,
        errorMessage: null
      };
      rerender();
    },

    OPP_CANCEL_INTAKE(_payload) {
      if (state.portfolio) {
        state.portfolio.intakeForm = null;
      }
      rerender();
    },

    OPP_SUBMIT_INTAKE(_payload, ctx) {
      if (!state.portfolio) return;
      const fields = extractFormFields(ctx?.element);
      if (!services.opportunityService) return;
      try {
        services.opportunityService.create({
          userId: DEFAULT_USER.id,
          title: (fields.title ?? '').trim(),
          problemStatement: (fields.problemStatement ?? '').trim(),
          scope: fields.scope ? String(fields.scope).trim() : null,
          proposedProjectType: fields.proposedProjectType ?? 'AD_HOC'
        });
        state.portfolio.intakeForm = null;
      } catch (err) {
        state.portfolio.intakeForm = {
          ...(state.portfolio.intakeForm ?? {}),
          title: fields.title ?? '',
          problemStatement: fields.problemStatement ?? '',
          scope: fields.scope ?? '',
          proposedProjectType: fields.proposedProjectType ?? 'AD_HOC',
          errorName: err.name ?? 'INTAKE_FAILED',
          errorMessage: err.message ?? ''
        };
        state.lastError = err;
      }
      rerender();
    },

    OPP_PROMOTE(payload) {
      if (!payload || !payload.opportunityId) return;
      if (!services.opportunityService) return;
      try {
        services.opportunityService.promote(payload.opportunityId);
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    OPP_DEFER(payload) {
      if (!payload || !payload.opportunityId) return;
      if (!services.opportunityService) return;
      const promptFn = globalThis.prompt ?? null;
      let deferredUntil = null;
      if (promptFn) {
        deferredUntil = promptFn('Defer until (YYYY-MM-DD)') ?? null;
      }
      if (!deferredUntil) {
        // Default: 14 days out if no prompt available.
        const d = new Date(services.clock.now());
        d.setDate(d.getDate() + 14);
        deferredUntil = d.toISOString().slice(0, 10);
      }
      try {
        services.opportunityService.defer(payload.opportunityId, { deferredUntil });
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    OPP_REJECT(payload) {
      if (!payload || !payload.opportunityId) return;
      if (!services.opportunityService) return;
      const promptFn = globalThis.prompt ?? null;
      let reason = null;
      if (promptFn) {
        reason = promptFn('Why reject? (at least 5 chars)') ?? null;
      }
      if (!reason || reason.length < 5) {
        // UI guard: without reason, bail.
        return;
      }
      try {
        services.opportunityService.reject(payload.opportunityId, { reason });
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    OPP_TOGGLE_EXPAND(payload) {
      if (!state.portfolio) return;
      if (!payload || !payload.opportunityId) return;
      if (state.portfolio.expandedOpportunityId === payload.opportunityId) {
        state.portfolio.expandedOpportunityId = null;
      } else {
        state.portfolio.expandedOpportunityId = payload.opportunityId;
      }
      rerender();
    },

    OPP_FILTER_CHANGE(payload, ctx) {
      if (!state.portfolio) return;
      let value = payload?.value;
      if (!value && ctx?.element && typeof ctx.element.value === 'string') {
        value = ctx.element.value;
      }
      if (typeof value === 'string') {
        state.portfolio.oppFilter = value;
        savePortfolioPrefs(services.repo, {
          oppFilter: state.portfolio.oppFilter,
          oppSort: state.portfolio.oppSort
        });
      }
      rerender();
    },

    OPP_SORT_CHANGE(payload, ctx) {
      if (!state.portfolio) return;
      let value = payload?.value;
      if (!value && ctx?.element && typeof ctx.element.value === 'string') {
        value = ctx.element.value;
      }
      if (typeof value === 'string') {
        state.portfolio.oppSort = value;
        savePortfolioPrefs(services.repo, {
          oppFilter: state.portfolio.oppFilter,
          oppSort: state.portfolio.oppSort
        });
      }
      rerender();
    },

    // ---- Sprint 7: Catalog view toggle (P0-T7) ------------------------------

    CATALOG_SET_VIEW(payload) {
      if (!payload || typeof payload.view !== 'string') return;
      state.catalogView = payload.view;
      rerender();
    },

    CATALOG_TOGGLE(payload) {
      if (!payload || !payload.catalogEntryId) return;
      if (!services.catalogService) return;
      try {
        services.catalogService.toggleEnabled(
          payload.catalogEntryId,
          DEFAULT_USER.id
        );
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    // ---- Sprint 9: Weekly composer --------------------------------------

    WEEK_PROPOSE(payload) {
      if (!services.weeklyComposerService) return;
      const weekStart =
        payload?.weekStart ?? computeMondayIso(services.clock.now());
      try {
        services.weeklyComposerService.proposeWeek({
          weekStart,
          userId: DEFAULT_USER.id,
          dailyCapacityMinutes: DEFAULT_USER.dailyCapacityMinutes
        });
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    WEEK_ACCEPT_DAY(payload) {
      if (!payload || !payload.weeklyCompositionId) return;
      if (typeof payload.dayIndex !== 'number') return;
      if (!services.weeklyComposerService) return;
      try {
        services.weeklyComposerService.acceptDay(
          payload.weeklyCompositionId,
          payload.dayIndex
        );
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    WEEK_ACCEPT_ALL(payload) {
      if (!payload || !payload.weeklyCompositionId) return;
      if (!services.weeklyComposerService) return;
      try {
        services.weeklyComposerService.acceptWeek(payload.weeklyCompositionId);
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    // ---- Sprint 10b Pass B: Portfolio project expand + step actions ----

    PORTFOLIO_TOGGLE_KAIZEN(payload) {
      if (!payload || typeof payload.kaizenId !== 'string') return;
      if (state.expandedKaizenId === payload.kaizenId) {
        state.expandedKaizenId = null;
      } else {
        state.expandedKaizenId = payload.kaizenId;
      }
      rerender();
    },

    KAIZEN_COMPLETE_STEP(payload) {
      if (!payload || !payload.kaizenId || !payload.catalogEntryId) return;
      try {
        services.kaizenService.completeStep({
          kaizenId: payload.kaizenId,
          catalogEntryId: payload.catalogEntryId,
          userId: DEFAULT_USER.id,
          sourceKind: 'portfolio'
        });
      } catch (err) {
        state.lastError = err;
        // Best-effort inline toast — fall back to console.warn if no global
        // alert exists (tests). Avoids blocking the render path.
        if (err && err.name === 'STEP_NOT_CURRENT') {
          // eslint-disable-next-line no-console
          console.warn('Complete next step first.', { kaizenId: payload.kaizenId });
        }
      }
      rerender();
    },

    KAIZEN_SCHEDULE_STEP_TODAY(payload) {
      if (!payload || !payload.kaizenId || !payload.catalogEntryId) return;
      const todayIso = services.clock.now().slice(0, 10);
      try {
        services.kaizenService.scheduleStep({
          kaizenId: payload.kaizenId,
          catalogEntryId: payload.catalogEntryId,
          targetDate: todayIso,
          userId: DEFAULT_USER.id
        });
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    KAIZEN_SCHEDULE_STEP_WEEK(payload) {
      if (!payload || !payload.kaizenId || !payload.catalogEntryId) return;
      // MVP: navigate to /#week; the user runs Plan this week to surface
      // the step on Monday of the current week. See SPRINT_10B_NOTES.md.
      if (typeof globalThis.location !== 'undefined') {
        globalThis.location.hash = '#week';
      }
      rerender();
    }
  };
}

/**
 * Extract form fields into a plain object. Duck-typed so tests can pass
 * a stub form element with a `.querySelectorAll()` that returns items
 * with `.name` + `.value` + `.type` + `.checked`.
 *
 * @param {any} form
 * @returns {Record<string, string>}
 */
export function extractFormFields(form) {
  if (!form) return {};
  // If the click target isn't the form itself, walk up to a closest form.
  let f = form;
  if (typeof f.closest === 'function') {
    const fallback = f.closest('form');
    if (fallback) f = fallback;
  }
  if (typeof f.querySelectorAll !== 'function') return {};
  const out = {};
  const fields = f.querySelectorAll('input, textarea, select');
  if (!fields || typeof fields[Symbol.iterator] !== 'function') return {};
  for (const el of fields) {
    const name = el.name ?? el.getAttribute?.('name');
    if (!name) continue;
    const type = el.type ?? 'text';
    if ((type === 'radio' || type === 'checkbox') && !el.checked) continue;
    out[name] = el.value ?? '';
  }
  return out;
}

/**
 * Boot the SPA. Called from `app.html` with `<script type="module">`.
 * Safe to call only from a browser environment.
 */
export function start() {
  /* istanbul ignore next — real DOM only */
  if (typeof document === 'undefined') {
    throw new Error('start(): no document available; must run in a browser.');
  }
  const services = buildServices();
  const state = createState();

  // Restore persisted Portfolio prefs (Sprint 7 P1-T3).
  const savedPrefs = loadPortfolioPrefs(services.repo);
  if (savedPrefs && typeof savedPrefs === 'object') {
    if (typeof savedPrefs.oppFilter === 'string') {
      state.portfolio.oppFilter = savedPrefs.oppFilter;
    }
    if (typeof savedPrefs.oppSort === 'string') {
      state.portfolio.oppSort = savedPrefs.oppSort;
    }
  }

  services.bus.subscribe(CycleProposed, () => {});
  services.bus.subscribe(CycleAccepted, () => {});
  services.bus.subscribe(CycleRejected, () => {});
  services.bus.subscribe(ComposerInfeasible, () => {});
  services.bus.subscribe(ActivityStarted, () => {});
  services.bus.subscribe(VarianceLogged, () => {});
  services.bus.subscribe(ReflectionStubbed, () => {});
  services.bus.subscribe(ReflectionCaptured, () => {});
  services.bus.subscribe(FrictionSignalCaptured, () => {});
  services.bus.subscribe(KaizenPromoted, () => {});
  services.bus.subscribe(KaizenBaselineLocked, () => {});
  services.bus.subscribe(KaizenRemeasurementStarted, () => {});
  services.bus.subscribe(KaizenRemeasured, () => {});
  services.bus.subscribe(KaizenClosed, () => {});
  services.bus.subscribe(KaizenAbandoned, () => {});
  services.bus.subscribe(OpportunityCreated, () => {});
  services.bus.subscribe(OpportunityPromoted, () => {});
  services.bus.subscribe(OpportunityDeferred, () => {});
  services.bus.subscribe(OpportunityRejected, () => {});
  services.bus.subscribe(WeeklyCycleProposed, () => {});
  services.bus.subscribe(WeeklyCycleAccepted, () => {});
  services.bus.subscribe(KaizenStepCompleted, () => {});
  services.bus.subscribe(KaizenStepScheduled, () => {});

  const rerender = () => renderApp(services, state);

  // Sprint 6 P0-T4: bridge ActivityCompleted → ReflectionService.stubOnClose,
  // then surface the ReflectionSheet. Keeps the service graph acyclic.
  services.bus.subscribe(ActivityCompleted, (payload) => {
    handleActivityCompleted(services, state, payload);
    rerender();
  });

  const listener = createRouteListener((parsed) => {
    state.route = parsed.route;
    state.params = parsed.params;
    rerender();
  });

  listener();
  globalThis.addEventListener('hashchange', listener);

  attachRootClickListener(APP_ROOT_ID, buildHandlers({ services, state, rerender }));

  // Sprint 10c: upgrade BROWSER_CATALOG (9 entries) → full 60-entry catalog
  // asynchronously after boot. Non-blocking so the app renders immediately
  // with the browser seed; re-renders once the fetch resolves.
  loadFullCatalogAsync(services, rerender);
}

/**
 * Fetch the full 60-entry catalog JSON and re-seed `catalogService` if the
 * fetch returns more entries than currently seeded. Silent on failure —
 * the app keeps using BROWSER_CATALOG so it never regresses.
 *
 * Only called from `start()`, which is itself browser-only.
 *
 * @param {object} services
 * @param {() => void} rerender
 * @returns {Promise<void>}
 */
export async function loadFullCatalogAsync(services, rerender) {
  try {
    const full = await getFullCatalog();
    if (!Array.isArray(full) || full.length === 0) return;
    const currentCount = Array.isArray(services.catalogService.list(DEFAULT_USER.id))
      ? services.catalogService.list(DEFAULT_USER.id).length
      : 0;
    if (full.length <= currentCount) return;
    services.catalogService.seed(full.map((c) => ({ ...c })));
    if (typeof rerender === 'function') rerender();
  } catch (err) {
    if (typeof console !== 'undefined') {
      // eslint-disable-next-line no-console
      console.warn('loadFullCatalogAsync: full catalog fetch failed; using BROWSER_CATALOG fallback', err);
    }
  }
}

/**
 * ActivityCompleted subscriber — stubs a Reflection and opens the
 * ReflectionSheet modal. Exported for tests.
 *
 * @param {object} services
 * @param {object} state
 * @param {{scheduledActivityId: string, compositionId?: string, actualEndAt?: string}} payload
 */
export function handleActivityCompleted(services, state, payload) {
  if (!payload || !payload.scheduledActivityId) return;
  const acts = services.repo.read('bamx:v1:activities') ?? {};
  const sa = acts[payload.scheduledActivityId];
  if (!sa) return;
  // Idempotent: if a Reflection already exists for this activity, just
  // open the sheet. Otherwise stub one.
  let reflection =
    services.reflectionService.getByScheduledActivityId(sa.id);
  if (!reflection) {
    try {
      const enrichedSa = {
        ...sa,
        userId:
          typeof sa.userId === 'string' && sa.userId.length > 0
            ? sa.userId
            : DEFAULT_USER.id
      };
      reflection = services.reflectionService.stubOnClose(enrichedSa);
    } catch (err) {
      if (err && err.name !== 'REFLECTION_ALREADY_EXISTS') {
        state.lastError = err;
        return;
      }
      reflection = services.reflectionService.getByScheduledActivityId(sa.id);
    }
  }
  if (!reflection || reflection.pending === false) return;
  // Resolve the catalog entry for display name + non-optional gating.
  const catalog = services.catalogService.list(DEFAULT_USER.id);
  const entry =
    (catalog ?? []).find((c) => c && c.id === sa.catalogEntryId) ?? null;
  state.reflectionSheet = {
    reflectionId: reflection.id,
    activityId: sa.id,
    activityName: entry?.name ?? sa.name ?? sa.id,
    plannedDurationMinutes: sa.plannedDurationMinutes ?? 0,
    planVsActualMinutes: reflection.planVsActualMinutes ?? 0,
    actualDurationMinutes:
      (sa.plannedDurationMinutes ?? 0) + (reflection.planVsActualMinutes ?? 0),
    isNonOptional: entry?.isNonOptional === true,
    frictionChecked: false
  };
}

// Auto-start when loaded as the page script (not when imported by tests).
/* istanbul ignore next — browser-only side effect */
if (
  typeof document !== 'undefined' &&
  typeof globalThis.__CADENCEPLAN_NO_AUTOSTART__ === 'undefined'
) {
  queueMicrotask(() => {
    try {
      start();
    } catch (err) {
      // eslint-disable-next-line no-console
      console.error('CadencePlan failed to start:', err);
    }
  });
}

export default {
  buildServices,
  buildComposerInput,
  renderApp,
  buildHandlers,
  computeDaysSinceSignup,
  extractFormFields,
  handleActivityCompleted,
  start,
  DEFAULT_USER,
  APP_ROOT_ID,
  parseHash,
  buildHash
};
