/**
 * CadencePlan MVP — single-page app entry (Sprint 4 + Sprint 5).
 *
 * Sprint 5 additions:
 *   - ActivityService / VarianceService wired
 *   - START_ACTIVITY handler (SCHEDULED → IN_PROGRESS)
 *   - OPEN_CLOSE_DIALOG + SUBMIT_CLOSE_DIALOG + CLOSE_CLOSE_DIALOG
 *   - OPEN_SKIP_MODAL + SUBMIT_SKIP_MODAL + CLOSE_SKIP_MODAL
 *   - Fine-tune drawer + re-compose pipeline (P1-T2)
 *   - InfeasibleBanner (P2-T1)
 *   - SmartDefaults ensureUser() on boot
 *
 * This file is the ONLY place that:
 *   - calls `document.*` (via `js/ui/mount.js` helpers)
 *   - reads `window.location.hash`
 *   - attaches `hashchange` listeners
 *   - writes state-dependent UI
 *
 * Every other module is pure: takes data in, returns strings / values out.
 */

import { boot } from './boot.js';
import { LocalStorageRepository } from './persistence/LocalStorageRepository.js';
import { EventBus } from './events/EventBus.js';
import { ClockService } from './services/ClockService.js';
import { CatalogService, CATALOG_KEY } from './services/CatalogService.js';
import { ComposerService } from './services/ComposerService.js';
import { VarianceService } from './services/VarianceService.js';
import { ActivityService } from './services/ActivityService.js';
import { ensureUser } from './services/SmartDefaults.js';
import {
  CycleProposed,
  CycleAccepted,
  CycleRejected,
  ComposerInfeasible,
  ActivityStarted,
  ActivityCompleted,
  VarianceLogged
} from './events/events.js';
import { BROWSER_CATALOG } from './catalog/browserSeed.js';
import { AppShell } from './ui/AppShell.js';
import { Today } from './ui/pages/Today.js';
import { PlaceholderPage } from './ui/pages/PlaceholderPage.js';
import { parseArtifactFields } from './ui/components/OutputArtifactDialog.js';
import {
  mountHtml,
  attachRootClickListener
} from './ui/mount.js';
import {
  createRouteListener,
  parseHash,
  buildHash
} from './ui/router.js';

/**
 * Default user — single-user MVP. A future sprint replaces this with a
 * real Settings-driven User row.
 */
export const DEFAULT_USER = Object.freeze({
  id: 'user_phil_mvp',
  name: 'Phil',
  email: 'phil@mediafier.ai',
  role: ['PRACTITIONER'],
  dailyCapacityMinutes: 480,
  workDays: [1, 2, 3, 4, 5],
  sprintAnchorDate: '2026-04-20',
  timezone: 'America/Los_Angeles',
  deepSlicePreference: '2x2h',
  createdAt: '2026-04-01T00:00:00Z'
});

const APP_ROOT_ID = 'app-root';

/**
 * Build the app services. Exported for tests and for the browser
 * bootstrapper. Side effects: reads/writes localStorage (via the repo),
 * seeds the catalog if empty.
 *
 * @param {{storage?: object, clock?: ClockService}} [deps]
 * @returns {object}
 */
export function buildServices(deps = {}) {
  const repo = new LocalStorageRepository({
    storage: deps.storage ?? globalThis.localStorage
  });
  const bus = new EventBus();
  const clock = deps.clock ?? new ClockService();

  boot(repo, { now: () => clock.nowDate() });

  const catalogService = new CatalogService({ repo });
  // Seed only if empty — idempotent across reloads.
  const existing = repo.read(CATALOG_KEY);
  if (!existing || Object.keys(existing).length === 0) {
    // Browser path uses the 9-entry browserSeed until fullCatalog.json is
    // present (generated by exportFullCatalog). Tests use the full
    // pipeline via their own CatalogService.seed() calls.
    catalogService.seed(BROWSER_CATALOG.map((c) => ({ ...c })));
  }

  const composerService = new ComposerService({
    repo,
    bus,
    clock,
    catalogService
  });
  const varianceService = new VarianceService({ repo, bus, clock });
  const activityService = new ActivityService({
    repo,
    bus,
    clock,
    varianceService,
    catalogService,
    composerService
  });

  // Ensure a User row exists with smart defaults (Sprint 5 P0-T2).
  ensureUser({
    repo,
    clock,
    userId: DEFAULT_USER.id,
    name: DEFAULT_USER.name,
    email: DEFAULT_USER.email
  });

  return {
    repo,
    bus,
    clock,
    catalogService,
    composerService,
    varianceService,
    activityService
  };
}

/**
 * Build a composer input from the default user. Accepts optional
 * overrides for the fine-tune drawer: `capacityMinutesOverride` and
 * `externalMinutesToday` land on composerInputsSnapshot.
 *
 * @param {ClockService} clock
 * @param {{capacityMinutesOverride?: number, externalMinutesToday?: number, activeKaizenId?: string|null}} [overrides]
 * @returns {object}
 */
export function buildComposerInput(clock, overrides = {}) {
  const date = clock.nowDate().toISOString().slice(0, 10);
  const effectiveCapacity =
    typeof overrides.capacityMinutesOverride === 'number'
      ? overrides.capacityMinutesOverride
      : DEFAULT_USER.dailyCapacityMinutes;
  const effectiveExternal =
    typeof overrides.externalMinutesToday === 'number'
      ? overrides.externalMinutesToday
      : 0;

  const input = {
    cycleType: 'DAILY',
    userId: DEFAULT_USER.id,
    date,
    role: [...DEFAULT_USER.role],
    dailyCapacityMinutes: effectiveCapacity,
    externalMinutesToday: effectiveExternal,
    // Sprint 5: expose the override for downstream Composition snapshot.
    capacityMinutesOverride:
      typeof overrides.capacityMinutesOverride === 'number'
        ? overrides.capacityMinutesOverride
        : null,
    sprintPhase: 'EXECUTION',
    sprintAnchorDate: DEFAULT_USER.sprintAnchorDate,
    user: {
      deepSlicePreference: DEFAULT_USER.deepSlicePreference,
      sprintAnchorDate: DEFAULT_USER.sprintAnchorDate
    },
    activeKaizen:
      overrides.activeKaizenId === null
        ? null
        : {
            id: overrides.activeKaizenId ?? 'k_cadenceplan_mvp',
            title: 'Ship CadencePlan MVP',
            state: 'ACTIVE',
            projectType: 'DMAIC',
            nextStepActivityNumber: 34
          },
    varianceQueue: [],
    priorCompositions: [],
    signals: {
      inboxOverThreshold: false,
      documentAwaitingReview: [],
      innovationStageReady: []
    },
    pdcaExperiment: null
  };
  return input;
}

/**
 * App state — the single render-fed object. `renderApp()` reads from
 * this (plus the repo) to produce HTML; handlers mutate it and call
 * renderApp() again.
 */
function createState() {
  return {
    route: 'today',
    params: {},
    composerLoading: false,
    infeasibleExplain: null,
    lastError: null,
    // Sprint 5: Fine-tune drawer state.
    fineTune: {
      open: false,
      capacityMinutes: DEFAULT_USER.dailyCapacityMinutes,
      externalMinutesToday: 0,
      activeKaizenId: 'k_cadenceplan_mvp',
      availableKaizens: [],
      // Pre-fine-tune snapshot for Cancel to restore.
      _snapshotBeforeChange: null
    },
    // Sprint 5: open dialog state (CLOSE artifact modal OR SKIP reason modal).
    openDialog: null
  };
}

/**
 * Render the entire app into the DOM. Pure shell around the pure page
 * components; real DOM only via `mountHtml`.
 *
 * @param {object} services
 * @param {object} state
 */
export function renderApp(services, state) {
  const { composerService } = services;
  let pageHtml;

  if (state.route === 'today') {
    const activeState = composerService.getActiveComposition(DEFAULT_USER.id);
    const daysSinceSignup = computeDaysSinceSignup(
      DEFAULT_USER.createdAt,
      services.clock.now()
    );
    pageHtml = Today({
      activeState,
      loading: state.composerLoading,
      isFirstRun: activeState === null && daysSinceSignup <= 1,
      infeasibleExplain: state.infeasibleExplain,
      adherence: {
        adherencePct: null,
        acceptancePct: null,
        kaizenDeltaPct: null,
        daysSinceSignup
      },
      nowIso: services.clock.now(),
      fineTune: state.fineTune,
      openDialog: state.openDialog
    });
  } else {
    pageHtml = PlaceholderPage({ route: state.route });
  }

  const shellHtml = AppShell({ route: state.route, pageHtml });
  mountHtml(APP_ROOT_ID, shellHtml);
}

/**
 * Compute days since signup, rounded down.
 *
 * @param {string} createdAtIso
 * @param {string} nowIso
 * @returns {number}
 */
export function computeDaysSinceSignup(createdAtIso, nowIso) {
  const a = new Date(createdAtIso);
  const b = new Date(nowIso);
  if (Number.isNaN(a.getTime()) || Number.isNaN(b.getTime())) return 0;
  const ms = b.getTime() - a.getTime();
  if (ms < 0) return 0;
  return Math.floor(ms / (24 * 60 * 60 * 1000));
}

/**
 * Look up an activity + its catalog entry. Returns {activity, entry} or
 * null if either is missing.
 *
 * @param {object} services
 * @param {string} activityId
 * @returns {{activity: object, entry: object|null} | null}
 */
function lookupActivity(services, activityId) {
  const acts = services.repo.read('bamx:v1:activities') ?? {};
  const activity = acts[activityId];
  if (!activity) return null;
  const list = services.catalogService.list(DEFAULT_USER.id);
  const entry = list.find((c) => c && c.id === activity.catalogEntryId) ?? null;
  return { activity, entry };
}

/**
 * Build the click handler registry.
 *
 * @param {{services: object, state: object, rerender: () => void}} scope
 */
export function buildHandlers(scope) {
  const { services, state, rerender } = scope;

  function runCompose(overrides) {
    state.composerLoading = true;
    state.lastError = null;
    state.infeasibleExplain = null;
    rerender();
    try {
      const input = buildComposerInput(services.clock, overrides);
      const result = services.composerService.composeDaily(input);
      if (result.state === 'INFEASIBLE') {
        state.infeasibleExplain = result.infeasible?.explain ?? [];
      }
    } catch (err) {
      state.lastError = err;
    } finally {
      state.composerLoading = false;
      rerender();
    }
  }

  return {
    AUTO_PLAN(_payload) {
      const ft = state.fineTune ?? null;
      const override =
        ft && typeof ft.capacityMinutes === 'number' &&
        ft.capacityMinutes !== DEFAULT_USER.dailyCapacityMinutes
          ? ft.capacityMinutes
          : undefined;
      runCompose({
        capacityMinutesOverride: override,
        externalMinutesToday: ft?.externalMinutesToday ?? 0,
        activeKaizenId: ft?.activeKaizenId ?? undefined
      });
    },

    ACCEPT(payload) {
      if (!payload || !payload.compositionId) return;
      try {
        services.composerService.accept(payload.compositionId);
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    EDIT(_payload) {
      // Edit (drag/drop composer) ships in Sprint 6.
      if (typeof globalThis.alert === 'function') {
        globalThis.alert('Edit composer ships in Sprint 6.');
      }
    },

    REJECT(payload) {
      if (!payload || !payload.compositionId) return;
      const confirmFn = globalThis.confirm ?? (() => true);
      const ok = confirmFn(
        "Reject today's plan? You'll need to build manually or wait for tomorrow."
      );
      if (!ok) return;
      try {
        services.composerService.reject(payload.compositionId);
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    // ---- Sprint 5: ScheduledActivity runtime -------------------------------

    START_ACTIVITY(payload) {
      if (!payload || !payload.activityId) return;
      try {
        services.activityService.start(payload.activityId);
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    OPEN_CLOSE_DIALOG(payload) {
      if (!payload || !payload.activityId) return;
      const looked = lookupActivity(services, payload.activityId);
      if (!looked) return;
      const schema = looked.entry?.outputArtifact?.schema ?? 'TEXT';
      state.openDialog = {
        kind: 'CLOSE',
        activityId: payload.activityId,
        schema,
        artifactDef: looked.entry?.outputArtifact ?? { schema, name: 'Output' }
      };
      rerender();
    },

    CLOSE_CLOSE_DIALOG(_payload) {
      state.openDialog = null;
      rerender();
    },

    SUBMIT_CLOSE_DIALOG(payload, ctx) {
      // Payload from form submit is the {activityId, schema} we stamped
      // on data-payload. The actual form field values are pulled off the
      // form element (if provided) via ctx.element.
      if (!payload || !payload.activityId) return;
      const schema = payload.schema ?? state.openDialog?.schema ?? 'TEXT';
      const fields = extractFormFields(ctx?.element);
      const ref = parseArtifactFields(schema, fields);
      try {
        services.activityService.close(payload.activityId, { outputArtifactRef: ref });
        state.openDialog = null;
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    OPEN_SKIP_MODAL(payload) {
      if (!payload || !payload.activityId) return;
      const looked = lookupActivity(services, payload.activityId);
      state.openDialog = {
        kind: 'SKIP',
        activityId: payload.activityId,
        activityName: looked?.entry?.name ?? looked?.activity?.name ?? payload.activityId
      };
      rerender();
    },

    CLOSE_SKIP_MODAL(_payload) {
      state.openDialog = null;
      rerender();
    },

    SUBMIT_SKIP_MODAL(payload, ctx) {
      if (!payload || !payload.activityId) return;
      const fields = extractFormFields(ctx?.element);
      const reasonCode = fields.reasonCode ?? null;
      const note = fields.note ?? null;
      try {
        services.activityService.skip(payload.activityId, { reasonCode, note });
        state.openDialog = null;
      } catch (err) {
        state.lastError = err;
      }
      rerender();
    },

    // ---- Sprint 5: Fine-tune drawer ----------------------------------------

    FINE_TUNE_TOGGLE(_payload) {
      if (!state.fineTune) return;
      if (!state.fineTune.open) {
        // Snapshot current settings before open, so Cancel can restore.
        state.fineTune._snapshotBeforeChange = {
          capacityMinutes: state.fineTune.capacityMinutes,
          externalMinutesToday: state.fineTune.externalMinutesToday,
          activeKaizenId: state.fineTune.activeKaizenId
        };
      }
      state.fineTune.open = !state.fineTune.open;
      rerender();
    },

    CAPACITY_CHANGE(payload) {
      if (!state.fineTune) return;
      if (!payload || typeof payload.minutes !== 'number') return;
      state.fineTune.capacityMinutes = payload.minutes;
      rerender();
    },

    EXTERNAL_MEETINGS_CHANGE(payload) {
      if (!state.fineTune) return;
      if (!payload || typeof payload.minutes !== 'number') return;
      state.fineTune.externalMinutesToday = payload.minutes;
      rerender();
    },

    PROJECT_FOCUS_CHANGE(payload, ctx) {
      if (!state.fineTune) return;
      let kaizenId = payload?.kaizenId ?? null;
      if (!kaizenId && ctx?.element && typeof ctx.element.value === 'string') {
        kaizenId = ctx.element.value || null;
      }
      state.fineTune.activeKaizenId = kaizenId;
      rerender();
    },

    FINE_TUNE_CANCEL(_payload) {
      if (!state.fineTune) return;
      const snap = state.fineTune._snapshotBeforeChange;
      if (snap) {
        state.fineTune.capacityMinutes = snap.capacityMinutes;
        state.fineTune.externalMinutesToday = snap.externalMinutesToday;
        state.fineTune.activeKaizenId = snap.activeKaizenId;
      }
      state.fineTune.open = false;
      state.fineTune._snapshotBeforeChange = null;
      rerender();
    },

    FINE_TUNE_APPLY(_payload) {
      // Discard the snapshot — the new values win.
      if (state.fineTune) {
        state.fineTune._snapshotBeforeChange = null;
        state.fineTune.open = false;
      }
      const ft = state.fineTune ?? {};
      const override =
        typeof ft.capacityMinutes === 'number' &&
        ft.capacityMinutes !== DEFAULT_USER.dailyCapacityMinutes
          ? ft.capacityMinutes
          : undefined;
      runCompose({
        capacityMinutesOverride: override,
        externalMinutesToday: ft.externalMinutesToday ?? 0,
        activeKaizenId: ft.activeKaizenId ?? undefined
      });
    }
  };
}

/**
 * Extract form fields into a plain object. Duck-typed so tests can pass
 * a stub form element with a `.querySelectorAll()` that returns items
 * with `.name` + `.value` + `.type` + `.checked`.
 *
 * @param {any} form
 * @returns {Record<string, string>}
 */
export function extractFormFields(form) {
  if (!form) return {};
  // If the click target isn't the form itself, walk up to a closest form.
  let f = form;
  if (typeof f.closest === 'function') {
    const fallback = f.closest('form');
    if (fallback) f = fallback;
  }
  if (typeof f.querySelectorAll !== 'function') return {};
  const out = {};
  const fields = f.querySelectorAll('input, textarea, select');
  if (!fields || typeof fields[Symbol.iterator] !== 'function') return {};
  for (const el of fields) {
    const name = el.name ?? el.getAttribute?.('name');
    if (!name) continue;
    const type = el.type ?? 'text';
    if ((type === 'radio' || type === 'checkbox') && !el.checked) continue;
    out[name] = el.value ?? '';
  }
  return out;
}

/**
 * Boot the SPA. Called from `app.html` with `<script type="module">`.
 * Safe to call only from a browser environment.
 */
export function start() {
  /* istanbul ignore next — real DOM only */
  if (typeof document === 'undefined') {
    throw new Error('start(): no document available; must run in a browser.');
  }
  const services = buildServices();
  const state = createState();

  services.bus.subscribe(CycleProposed, () => {});
  services.bus.subscribe(CycleAccepted, () => {});
  services.bus.subscribe(CycleRejected, () => {});
  services.bus.subscribe(ComposerInfeasible, () => {});
  services.bus.subscribe(ActivityStarted, () => {});
  services.bus.subscribe(ActivityCompleted, () => {});
  services.bus.subscribe(VarianceLogged, () => {});

  const rerender = () => renderApp(services, state);

  const listener = createRouteListener((parsed) => {
    state.route = parsed.route;
    state.params = parsed.params;
    rerender();
  });

  listener();
  globalThis.addEventListener('hashchange', listener);

  attachRootClickListener(APP_ROOT_ID, buildHandlers({ services, state, rerender }));
}

// Auto-start when loaded as the page script (not when imported by tests).
/* istanbul ignore next — browser-only side effect */
if (
  typeof document !== 'undefined' &&
  typeof globalThis.__CADENCEPLAN_NO_AUTOSTART__ === 'undefined'
) {
  queueMicrotask(() => {
    try {
      start();
    } catch (err) {
      // eslint-disable-next-line no-console
      console.error('CadencePlan failed to start:', err);
    }
  });
}

export default {
  buildServices,
  buildComposerInput,
  renderApp,
  buildHandlers,
  computeDaysSinceSignup,
  extractFormFields,
  start,
  DEFAULT_USER,
  APP_ROOT_ID,
  parseHash,
  buildHash
};
